### ISSUE TITLE
Get plugin assets for banner and icon

### ISSUE THREAD

**Issue by cameronterry** [cameronterry/dark-matter#11]
Based on the guide here; https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

Need four assets put together at some point which are;

* Normal Banner: banner-772x250.(jpg|png)
* High-DPI (Retina): banner-1544x500.(jpg|png)

* icon-128x128.(png|jpg)
* icon-256x256.(png|jpg)

**Comment by cameronterry** [comment]
If we continue the trail of thought on tying the graphics to visualisation of the scientist the release is named after. For Kapteyn it would seem is defining contribution was himself modelling and helping future scientists put together a more accurate model / structure of the Milky Way.

So that could be a focus for the banners if we continue that trail of thought.

**Comment by baz1414** [comment]
Yeah that seems like a logical course of action
