### ISSUE TITLE
Missing filter to set domain permission check

### ISSUE THREAD

**Issue by svandragt** [cameronterry/dark-matter#51]
Would be good to be able to filter the permission regarding who can manage domains.

currently it's the following, despite the settings menu being part of the site (logic then dictates site admins should be able to do this).
```
public function create_item_permissions_check( $request ) {
		return current_user_can( 'upgrade_network' );
	}
```

**Comment by cameronterry** [comment]
This has been introduced in release [2.1.2](https://github.com/cameronterry/dark-matter/releases/tag/2.1.2). Therefore closing this issue as fixed.
